# This file is auto-generated by the viter release pipeline.
# See: https://github.com/yuriishunkin/viter/tree/main/brew
#
# To update manually, run from the viter repo:
#   ./brew/update_tap.sh <version> <sha256> --tap-dir <path-to-this-repo>

cask "viter" do
  version "1.0.0"
  sha256 "a810249f13a5474aca266cb4bd41bdbbbbddf7aa930989cba0c05276b2a67dff"

  url "https://github.com/yuriishunkin/viter/releases/download/v#{version}/Viter-v#{version}.zip"
  name "Viter"
  desc "Fan control and thermal monitoring for macOS"
  homepage "https://github.com/yuriishunkin/viter"

  depends_on macos: ">= :sonoma"

  app "Viter.app"

  zap trash: [
    "~/Library/Preferences/com.yuriishunkin.Viter.plist",
  ]
end
